= https://plugins.gradle.org/plugin/com.github.dkorotych.gradle-maven-exec[gradle-maven-exec-plugin]

Gradle plugin which provides a Maven exec task

image:https://img.shields.io/github/checks-status/dkorotych/gradle-maven-exec-plugin/master[GitHub branch status]
image:https://codecov.io/gh/dkorotych/gradle-maven-exec-plugin/graph/badge.svg?token=1zdFJxubOd["codecov", link="https://codecov.io/gh/dkorotych/gradle-maven-exec-plugin"]
image:https://app.codacy.com/project/badge/Grade/7c2907ecd1d749deb5c3765bd86cbf72["Codacy code quality", link="https://app.codacy.com/gh/dkorotych/gradle-maven-exec-plugin/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade"]
image:https://app.codacy.com/project/badge/Coverage/7c2907ecd1d749deb5c3765bd86cbf72["Codacy code quality", link="https://app.codacy.com/gh/dkorotych/gradle-maven-exec-plugin/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_coverage"]
image:https://img.shields.io/github/license/dkorotych/gradle-maven-exec-plugin[GitHub License]


== Installing

Releases of this plugin are hosted
on https://login.gradle.org/plugin/com.github.dkorotych.gradle-maven-exec[Gradle's Plugin Repository].
Apply the plugin to your project using one of the two methods below.

==== Using the https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block[plugins DSL]:

[source,groovy]
----
plugins {
    id "com.github.dkorotych.gradle-maven-exec" version "4.0.0"
}
----

==== Using https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application[legacy plugin application]:

[source,groovy]
----
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.dkorotych.gradle.maven.exec:gradle-maven-exec-plugin:4.0.0"
    }
}

apply plugin: "com.github.dkorotych.gradle-maven-exec"
----

== Usage

This plugin enables a `MavenExec` task type in your buildscript which behaves exactly like a typical Gradle
`Exec` task, except that it normalizes calls to work across operating systems.
It does this by:

1. Automatic generation of correct command line
2. Used Maven Wrapper if it exists in a project
3. It is forbidden to direct control of the command line arguments
4. Removing unsupported command-line options when you call different Maven versions

To define a `MavenExec` task, simply specify the task `type`:

[source,groovy]
----
task rebuild(type: MavenExec) {
    goals 'clean', 'package'
}
----

or passing the advanced command-line options:

[source,groovy]
----
task generateSite(type: MavenExec) {
    goals 'clean', 'package', 'site'
    options {
        threads = '2C'
        activateProfiles = ['development', 'site']
        define = [
            'groupId'   : 'com.github.application',
            'artifactId': 'parent'
        ]
    }
}
----

or used it without options closure:

[source,groovy]
----
task generateSite(type: MavenExec) {
    goals 'archetype:generate'
    define([
        'groupId'            : 'com.mycompany.app',
        'artifactId'         : 'my-app',
        'archetypeArtifactId': 'maven-archetype-quickstart',
        'interactiveMode'    : 'false'
    ])
    quiet true
}
----

or even a direct call to control Maven from any task

[source,groovy]
----
task generateAndExecuteApplication {
    doLast {
        buildDir.mkdirs()
        def groupId = 'com.mycompany.app'
        def application = 'my-app'
        def applicationDir = file("$buildDir/$application")
        delete applicationDir
        mavenexec {
            workingDir buildDir
            goals 'archetype:generate'
            define([
                    'groupId'            : groupId,
                    'artifactId'         : application,
                    'archetypeArtifactId': 'maven-archetype-quickstart',
                    'interactiveMode'    : 'false'
            ])
            quiet true
        }
        mavenexec {
            workingDir applicationDir
            goals 'package'
            threads '2C'
            quiet true
        }
        javaexec {
            workingDir applicationDir
            classpath file("$applicationDir/target/$application-1.0-SNAPSHOT.jar")
            main "${groupId}.App"
        }
    }
}
----


== F.A.Q.

If you run into any issues,
consult the [F.A.Q.](https://github.com/dkorotych/gradle-maven-exec-plugin/blob/master/FAQ.md) first.
