type: specs.openrewrite.org/v1beta/recipe
name: com.github.dkorotych.gradle.maven.exec.MavenExecPlugin
recipeList:
  - org.openrewrite.gradle.DependencyUseStringNotation
  - org.openrewrite.java.logging.PrintStackTraceToLogError
  - org.openrewrite.java.logging.slf4j.ParameterizedLogging
  - org.openrewrite.java.logging.slf4j.ConvertLogMessageMessageOnlyToLogMessageAndThrowable
  - org.openrewrite.java.testing.junit5.JUnit5BestPractices
  - org.openrewrite.java.testing.mockito.Mockito3to4Migration
  - org.openrewrite.java.testing.cleanup.BestPractices
  - org.openrewrite.java.testing.assertj.Assertj
  - org.openrewrite.java.testing.assertj.JUnitToAssertj
  - org.openrewrite.java.cleanup.CommonStaticAnalysis
  - org.openrewrite.java.cleanup.Cleanup
  - org.openrewrite.java.cleanup.JavaApiBestPractices
