name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - master

jobs:
#  build:
#    if: "!contains(github.event.head_commit.message, 'skip ci')"
#    runs-on: ubuntu-latest
#    steps:
#      - uses: styfle/cancel-workflow-action@0.9.1
#        with:
#          access_token: ${{ github.token }}
#      - uses: actions/checkout@v3
#      - name: Set up JDK 8
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: 8
#          cache: 'gradle'
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build

  validate:
    name: Validate on ${{ matrix.os }} and Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - '8'
#          - '11'
#          - '17'
        os:
#          - 'ubuntu-latest'
#          - 'macos-latest'
          - 'windows-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set MAVEN_HOME
        run: "echo MAVEN_HOME=$(mvn --version | select-string 'Maven home: (.+)$' | % { $_.Matches.Groups[1].Value }) >> $GITHUB_ENV"
      - if: ${{ matrix.os != 'windows-latest' }}
        name: Set MAVEN_HOME
        run: echo "MAVEN_HOME=$(mvn --version | grep 'Maven home:' | cut -d ":" -f 2 | cut -c 2-)" >> $GITHUB_ENV
      - run: echo "$GITHUB_ENV"
      - name: Run plugin tests
        run: gradle functionalTest --no-daemon
