# See: https://github.com/gradle/wrapper-validation-action
name: "Official Gradle Wrapper Validation Action"
on: [ push, pull_request ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
