name: Java CI with Gradle

on: [ push, pull_request ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'
      - name: Set MAVEN_HOME
        run: echo "MAVEN_HOME=$(mvn --version | grep 'Maven home:' | cut -d ":" -f 2 | cut -c 2-)" >> $GITHUB_ENV
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: check jacocoTestReport
      - uses: codecov/codecov-action@v2
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: LINUX
          fail_ci_if_error: true
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6

  validate:
    name: Validate on ${{ matrix.os }} and Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
          - 18
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set MAVEN_HOME (Windows)
        run: |
          mvn --version |
          select-string 'Maven home: (.+)$' |
          % { 'MAVEN_HOME=' + $_.Matches.Groups[1].Value } |
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - if: ${{ matrix.os != 'windows-latest' }}
        name: Set MAVEN_HOME
        run: echo "MAVEN_HOME=$(mvn --version | grep 'Maven home:' | cut -d ":" -f 2 | cut -c 2-)" >> $GITHUB_ENV
      - uses: gradle/gradle-build-action@v2
        if: ${{ matrix.java < 17 }}
        name: Run plugin tests
        with:
          gradle-version: wrapper
          arguments: :functionalTest --tests "com.github.dkorotych.gradle.maven.exec.MavenExecPluginFunctionalTest"
      - uses: gradle/gradle-build-action@v2
        if: ${{ matrix.java >= 17 }}
        name: Run plugin tests
        with:
          gradle-version: current
          arguments: :functionalTest --tests "com.github.dkorotych.gradle.maven.exec.MavenExecPluginFunctionalTest"
